"""initial_budget_schema

Revision ID: 242be018a988
Revises: 
Create Date: 2026-05-19 16:35:40.904894
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '242be018a988'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budgets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('monthly_limit', sa.Float(), nullable=False),
    sa.Column('spent_amount', sa.Float(), nullable=True),
    sa.Column('alert_threshold', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='budget_service'
    )
    op.create_index(op.f('ix_budget_service_budgets_category_id'), 'budgets', ['category_id'], unique=False, schema='budget_service')
    op.create_index(op.f('ix_budget_service_budgets_user_id'), 'budgets', ['user_id'], unique=False, schema='budget_service')
    op.create_table('saving_pots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('target_amount', sa.Float(), nullable=False),
    sa.Column('current_amount', sa.Float(), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', name='potstatus', schema='budget_service'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='budget_service'
    )
    op.create_index(op.f('ix_budget_service_saving_pots_user_id'), 'saving_pots', ['user_id'], unique=False, schema='budget_service')
    op.create_table('pot_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pot_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('DEPOSIT', 'WITHDRAWAL', name='transactiontype', schema='budget_service'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['pot_id'], ['budget_service.saving_pots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='budget_service'
    )
    op.create_index(op.f('ix_budget_service_pot_transactions_pot_id'), 'pot_transactions', ['pot_id'], unique=False, schema='budget_service')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_budget_service_pot_transactions_pot_id'), table_name='pot_transactions', schema='budget_service')
    op.drop_table('pot_transactions', schema='budget_service')
    op.drop_index(op.f('ix_budget_service_saving_pots_user_id'), table_name='saving_pots', schema='budget_service')
    op.drop_table('saving_pots', schema='budget_service')
    op.drop_index(op.f('ix_budget_service_budgets_user_id'), table_name='budgets', schema='budget_service')
    op.drop_index(op.f('ix_budget_service_budgets_category_id'), table_name='budgets', schema='budget_service')
    op.drop_table('budgets', schema='budget_service')
    # ### end Alembic commands ###
